### ISSUE TITLE
Change from Baseline graph does not respond to Dataset selector

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-frontend#343]
The Dataset selector on CfB may be supposed to set the baseline for the %change graphs. It doesn't.

Alternatively, the baseline is fixed, and this selector is superfluous. 

Figure out which is true; then make the required changes.

@corviday as we discussed you have some information to add to this.

**Comment by corviday** [comment]
I don't remember what information I was planning to add here. I believe the [original intent](https://github.com/pacificclimate/climate-explorer-frontend/issues/175) was a fixed baseline, with the possibility to make it selectable somewhere down the line. I think we now want a selectable baseline.

**Comment by corviday** [comment]
We are once again baffled by this, so I have done a little more investigation. AnomalyAnnualCycleGraph has a dropdown because it is an instance of AnnualCycleGraph, which has a dropdown. The dropdown doesn't do anything except force a rerender of the graph.

Easy fix: pass a prop to AnnualCycleGraph telling it whether or not t render a drop down

Real fix: implement selectable baselines (this probably requires refactoring how the graphs work substantially)
