### ISSUE TITLE
remove or reconsider npm audit --fix in github workfiles

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#437]
Currently, we use the `npm audit --fix` command to detect when a package has a security issue and automatically upgrade to a newer version of the package if the newer version is listed as non-breaking. This happens while building docker images. 

The downside to this is that we are applying unpredictable upgrades a human has not reviewed to every docker image after a human has checked its functionality but before it is deployed to production. We would like to replace this with a system that includes human oversight of these upgrades.

**Comment by Nospamas** [comment]
Additional Notes:

This happens during the docker build of our project. When applying `npm audit fix --quiet` fixes that fail (because it can't solve critical issues) cause the build to fail outright. As a result I've removed this call for now as part of #445 which does a code warning cleanup, adds prettier and updates some package versions.

Logged #461 to track the project update.

**Comment by Nospamas** [comment]
Closing this as we'll track it elsewhere.
